name: deepom
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge

dependencies:
  - python=3.10.8
  - pytorch-cuda=11.6
  - torchvision
  - monai
  - fire
  - jupyter
  - more-itertools
  - nd2reader
  - gitpython
  - pyyaml
  - pytest
  - numpy
  - scipy
  - pandas
  - joblib
  - ipython
  - tqdm
  - matplotlib
  - seaborn
  - statsmodels
  - tensorboard
  - scikit-learn
  - scikit-image
  - imageio
  - biopython
  - numba
  - wandb